/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WcButton {
    /**
    * 是否禁用
    */
    'disabled': boolean;
    /**
    * Icon
    */
    'icon': string;
    /**
    * 风格
    */
    'theme': string;
  }
  interface WcButtonAttributes extends StencilHTMLAttributes {
    /**
    * 是否禁用
    */
    'disabled'?: boolean;
    /**
    * Icon
    */
    'icon'?: string;
    /**
    * 点击事件
    */
    'onOnClick'?: (event: CustomEvent) => void;
    /**
    * 风格
    */
    'theme'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WcButton': Components.WcButton;
  }

  interface StencilIntrinsicElements {
    'wc-button': Components.WcButtonAttributes;
  }


  interface HTMLWcButtonElement extends Components.WcButton, HTMLStencilElement {}
  var HTMLWcButtonElement: {
    prototype: HTMLWcButtonElement;
    new (): HTMLWcButtonElement;
  };

  interface HTMLElementTagNameMap {
    'wc-button': HTMLWcButtonElement
  }

  interface ElementTagNameMap {
    'wc-button': HTMLWcButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
